version: '3'

services:
  nestjs:
    build: .
    ports:
      - "8080:8080"    
    depends_on:
      - zerotier

  zerotier:
    image: zerotier/zerotier
    network_mode: "host"
    restart: unless-stopped
    privileged: true